using System.Net;
using System.Text.Json;
using FluentValidation;
using System.Linq;

namespace CredentialFlow.Api.Middleware;

/// Centralized exception handling middleware.
/// Converts application exceptions into consistent
/// HTTP responses and prevents stack traces from
/// being exposed to API consumers.
public class GlobalExceptionMiddleware
{
    private readonly RequestDelegate _next;
    private readonly ILogger<GlobalExceptionMiddleware> _logger;

    public GlobalExceptionMiddleware(
        RequestDelegate next,
        ILogger<GlobalExceptionMiddleware> logger)
    {
        _next = next;
        _logger = logger;
    }

    public async Task InvokeAsync(HttpContext context)
    {
        try
        {
            await _next(context);
        }
        catch (Exception ex)
        {
            _logger.LogError(
                ex,
                "Unhandled exception occurred.");

            context.Response.ContentType =
                "application/json";

            object response;

            switch (ex)
            {
                // Validation failures generated by FluentValidation.
                // These indicate bad client input and should return 400.
                case ValidationException validationException:

                    context.Response.StatusCode =
                        (int)HttpStatusCode.BadRequest;

                    response = new
                    {
                        StatusCode = 400,
                        Message = "Validation failed",
                        Errors = validationException.Errors
                            .Select(x => x.ErrorMessage)
                    };

                    break;

                // Missing files are treated as a resource not found.
                case FileNotFoundException:

                    context.Response.StatusCode =
                        (int)HttpStatusCode.NotFound;

                    response = new
                    {
                        StatusCode = 404,
                        Message = ex.Message
                    };

                    break;

                // Catch-all for anything unexpected.
                default:

                    context.Response.StatusCode =
                        (int)HttpStatusCode.InternalServerError;

                    response = new
                    {
                        StatusCode = 500,
                        Message = "An unexpected error occurred."
                    };

                    break;
            }

            await context.Response.WriteAsync(
                JsonSerializer.Serialize(response));
        }
    }
}
